[2025-05-02T19:19:38.448+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T19:19:38.455+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T19:19:38.456+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-05-02T19:19:38.457+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-05-02T19:19:38.457+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-05-02T19:19:38.465+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): store_user> on 2025-05-01 00:00:00+00:00
[2025-05-02T19:19:38.468+0000] {standard_task_runner.py:55} INFO - Started process 1809 to run task
[2025-05-02T19:19:38.470+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpg_lljjxt']
[2025-05-02T19:19:38.471+0000] {standard_task_runner.py:83} INFO - Job 53: Subtask store_user
[2025-05-02T19:19:38.502+0000] {task_command.py:388} INFO - Running <TaskInstance: user_processing.store_user scheduled__2025-05-01T00:00:00+00:00 [running]> on host b08efc87d46b
[2025-05-02T19:19:38.531+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2025-05-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-05-01T00:00:00+00:00
[2025-05-02T19:19:38.533+0000] {postgres.py:158} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2025-05-02T19:19:38.536+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2025-05-02T19:19:38.537+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_processing.py", line 35, in _store_user
    filename = '/tmp/processed_user.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 166, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.BadCopyFileFormat: missing data for column "lastname"
CONTEXT:  COPY users, line 2: "e.com"

[2025-05-02T19:19:38.541+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=user_processing, task_id=store_user, execution_date=20250501T000000, start_date=20250502T191938, end_date=20250502T191938
[2025-05-02T19:19:38.545+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 53 for task store_user (missing data for column "lastname"
CONTEXT:  COPY users, line 2: "e.com"
; 1809)
[2025-05-02T19:19:38.568+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-05-02T19:19:38.578+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
