[2025-04-29T04:42:44.667+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2025-04-29T04:42:43.263313+00:00 [queued]>
[2025-04-29T04:42:44.670+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2025-04-29T04:42:43.263313+00:00 [queued]>
[2025-04-29T04:42:44.670+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-29T04:42:44.670+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-04-29T04:42:44.670+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-29T04:42:44.675+0000] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): is_api_available> on 2025-04-29 04:42:43.263313+00:00
[2025-04-29T04:42:44.678+0000] {standard_task_runner.py:55} INFO - Started process 506 to run task
[2025-04-29T04:42:44.679+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2025-04-29T04:42:43.263313+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpo3_zq7xx']
[2025-04-29T04:42:44.680+0000] {standard_task_runner.py:83} INFO - Job 41: Subtask is_api_available
[2025-04-29T04:42:44.704+0000] {task_command.py:388} INFO - Running <TaskInstance: user_processing.is_api_available manual__2025-04-29T04:42:43.263313+00:00 [running]> on host b08efc87d46b
[2025-04-29T04:42:44.730+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2025-04-29T04:42:43.263313+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-29T04:42:43.263313+00:00
[2025-04-29T04:42:44.731+0000] {http.py:122} INFO - Poking: api/
[2025-04-29T04:42:44.736+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2025-04-29T04:42:44.791+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/urllib3/connectionpool.py:1052: InsecureRequestWarning: Unverified HTTPS request is being made to host 'randomuser.me'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

[2025-04-29T04:42:58.158+0000] {base.py:228} INFO - Success criteria met. Exiting.
[2025-04-29T04:42:58.166+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20250429T044243, start_date=20250429T044244, end_date=20250429T044258
[2025-04-29T04:42:58.199+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-04-29T04:42:58.217+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
