[2024-12-26T02:46:25.118+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2024-12-26T02:46:23.652840+00:00 [queued]>
[2024-12-26T02:46:25.121+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2024-12-26T02:46:23.652840+00:00 [queued]>
[2024-12-26T02:46:25.121+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-12-26T02:46:25.121+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-12-26T02:46:25.121+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-12-26T02:46:25.126+0000] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-12-26 02:46:23.652840+00:00
[2024-12-26T02:46:25.128+0000] {standard_task_runner.py:55} INFO - Started process 26190 to run task
[2024-12-26T02:46:25.130+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2024-12-26T02:46:23.652840+00:00', '--job-id', '217', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmprs_l4p9n']
[2024-12-26T02:46:25.130+0000] {standard_task_runner.py:83} INFO - Job 217: Subtask is_api_available
[2024-12-26T02:46:25.152+0000] {task_command.py:388} INFO - Running <TaskInstance: user_processing.is_api_available manual__2024-12-26T02:46:23.652840+00:00 [running]> on host 44e036a430cc
[2024-12-26T02:46:25.176+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-12-26T02:46:23.652840+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-26T02:46:23.652840+00:00
[2024-12-26T02:46:25.177+0000] {http.py:122} INFO - Poking: api/
[2024-12-26T02:46:25.180+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2024-12-26T02:46:25.263+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/urllib3/connectionpool.py:1052: InsecureRequestWarning: Unverified HTTPS request is being made to host 'randomuser.me'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

[2024-12-26T02:46:25.318+0000] {base.py:228} INFO - Success criteria met. Exiting.
[2024-12-26T02:46:25.323+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20241226T024623, start_date=20241226T024625, end_date=20241226T024625
[2024-12-26T02:46:25.349+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-12-26T02:46:25.367+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
