[2025-04-25T00:25:23.226+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2025-04-25T00:25:22.131743+00:00 [queued]>
[2025-04-25T00:25:23.230+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2025-04-25T00:25:22.131743+00:00 [queued]>
[2025-04-25T00:25:23.230+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-25T00:25:23.230+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-04-25T00:25:23.230+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-25T00:25:23.235+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_table> on 2025-04-25 00:25:22.131743+00:00
[2025-04-25T00:25:23.237+0000] {standard_task_runner.py:55} INFO - Started process 187 to run task
[2025-04-25T00:25:23.238+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2025-04-25T00:25:22.131743+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp9v16pi08']
[2025-04-25T00:25:23.238+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask create_table
[2025-04-25T00:25:23.259+0000] {task_command.py:388} INFO - Running <TaskInstance: user_processing.create_table manual__2025-04-25T00:25:22.131743+00:00 [running]> on host b08efc87d46b
[2025-04-25T00:25:23.282+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2025-04-25T00:25:22.131743+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-25T00:25:22.131743+00:00
[2025-04-25T00:25:23.283+0000] {sql.py:254} INFO - Executing: CREATE TABLE IF NOT EXISTS users (
            firstname TEXT NOT NULL,
            lastname TEXT NOT NULL,
            country TEXT NOT NULL,
            username TEXT NOT NULL,
            password TEXT NOT NULL,
            email TEXT NOT NULL);
[2025-04-25T00:25:23.289+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2025-04-25T00:25:23.290+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=user_processing, task_id=create_table, execution_date=20250425T002522, start_date=20250425T002523, end_date=20250425T002523
[2025-04-25T00:25:23.293+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task create_table (The conn_id `postgres` isn't defined; 187)
[2025-04-25T00:25:23.337+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-25T00:25:23.348+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
