[2025-06-04T23:10:10.725+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2025-06-03T00:00:00+00:00 [queued]>
[2025-06-04T23:10:10.730+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2025-06-03T00:00:00+00:00 [queued]>
[2025-06-04T23:10:10.730+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-06-04T23:10:10.730+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-06-04T23:10:10.730+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-06-04T23:10:10.736+0000] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): is_api_available> on 2025-06-03 00:00:00+00:00
[2025-06-04T23:10:10.738+0000] {standard_task_runner.py:55} INFO - Started process 81 to run task
[2025-06-04T23:10:10.740+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2025-06-03T00:00:00+00:00', '--job-id', '695', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpvs1_4k5p']
[2025-06-04T23:10:10.742+0000] {standard_task_runner.py:83} INFO - Job 695: Subtask is_api_available
[2025-06-04T23:10:10.772+0000] {task_command.py:388} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2025-06-03T00:00:00+00:00 [running]> on host 74c05f868d26
[2025-06-04T23:10:10.804+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2025-06-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-06-03T00:00:00+00:00
[2025-06-04T23:10:10.804+0000] {http.py:122} INFO - Poking: api/
[2025-06-04T23:10:10.811+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2025-06-04T23:10:10.961+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/urllib3/connectionpool.py:1052: InsecureRequestWarning: Unverified HTTPS request is being made to host 'randomuser.me'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

[2025-06-04T23:10:11.031+0000] {base.py:228} INFO - Success criteria met. Exiting.
[2025-06-04T23:10:11.037+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20250603T000000, start_date=20250604T231010, end_date=20250604T231011
[2025-06-04T23:10:11.084+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-06-04T23:10:11.098+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
