[2025-01-09T23:31:34.384+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-01-09T23:31:34.392+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-01-09T23:31:34.392+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-01-09T23:31:34.392+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-01-09T23:31:34.393+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-01-09T23:31:34.401+0000] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): is_api_available> on 2025-01-08 00:00:00+00:00
[2025-01-09T23:31:34.403+0000] {standard_task_runner.py:55} INFO - Started process 64 to run task
[2025-01-09T23:31:34.404+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2025-01-08T00:00:00+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpw3iyhdcb']
[2025-01-09T23:31:34.405+0000] {standard_task_runner.py:83} INFO - Job 251: Subtask is_api_available
[2025-01-09T23:31:34.436+0000] {task_command.py:388} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2025-01-08T00:00:00+00:00 [running]> on host 44e036a430cc
[2025-01-09T23:31:34.468+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2025-01-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-01-08T00:00:00+00:00
[2025-01-09T23:31:34.470+0000] {http.py:122} INFO - Poking: api/
[2025-01-09T23:31:34.473+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2025-01-09T23:31:34.678+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/urllib3/connectionpool.py:1052: InsecureRequestWarning: Unverified HTTPS request is being made to host 'randomuser.me'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

[2025-01-09T23:31:34.929+0000] {base.py:228} INFO - Success criteria met. Exiting.
[2025-01-09T23:31:34.933+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20250108T000000, start_date=20250109T233134, end_date=20250109T233134
[2025-01-09T23:31:34.976+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-01-09T23:31:34.993+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
